### ISSUE TITLE
#US05 Historial de turnos

### ISSUE THREAD

**Issue by leandros1793** [ReservasMedicasMobile/ReservasMedicasMobile#32]
Como usuario de la aplicación móvil, quiero acceder a una sección donde pueda visualizar el historial de mis reservas, para tener un registro claro y detallado de mis citas médicas pasadas.

**Criterios de aceptación:**

- La sección debe ofrecer una vista clara y organizada del historial de reservas.
- El usuario debe poder ver detalles relevantes de cada reserva, como fecha, hora, especialidad y médico.
- La interfaz debe ser fácil de usar y adaptarse a diferentes tamaños y orientaciones de pantalla.

### Tareas:
- [x] #33
- [x] #34

**Comment by matiassorrentino** [comment]
Realizado.
