### ISSUE TITLE
#TK16: Crear un diseño visual para el dashboard

### ISSUE THREAD

**Issue by leandros1793** [ReservasMedicasMobile/ReservasMedicasMobile#33]
- Crear un diseño visual para el dashboard, asegurando que sea intuitivo y fácil       de navegar, con una disposición clara de las secciones que incluirán el historial de reservas y otros datos relevantes. Garantizar que se adapte correctamente a diferentes dispositivos y orientaciones sin problemas de diseño.

**Comment by matiassorrentino** [comment]
Realizado.
