### ISSUE TITLE
#US06 Cancelar turnos

### ISSUE THREAD

**Issue by leandros1793** [ReservasMedicasMobile/ReservasMedicasMobile#35]
Como usuario quiero cancelar el turno con antelación para liberar ese horario y evitar cargos.

**Criterios de aceptación:**

- Brindar un aviso cuando la cancelación del turno sea exitosa o errónea, estipulado por el tiempo de aceptación del sistema.
- La interfaz de usuario debe ser intuitiva y responsive, para lograr una experiencia de usuario satisfactoria.

### Tareas:
- [x] #36
- [x] #38
- [x] #37

**Comment by sinistri** [comment]
Tomo esta tarea..
