### ISSUE TITLE
(BUG) INICIO DE SESION - La sesion no se cierra por inactividad

### ISSUE THREAD

**Issue by Jesica-A** [ReservasMedicasMobile/ReservasMedicasMobile#75]
### Descripcion: 
Al estar inactivo durante mucho tiempo, la aplicacion no cierra la sesión y se mantiene siempre abierta al menos que el usuario la cierre manualmente desde la aplicación.
### Severidad: 
Media
### Prioridad: 
Media
### Entorno: 
Dispositivos Android

### Pasos para reproducir:
1. Navegar a la pantalla "Iniciar sesion"
2. Completar los campos con credenciales validas (campo Usuario: 11222333, campo Contraseña: Pepe1997*)
3. Seleccionar el boton "Iniciar sesion"
4. Iniciada la sesion, dejar abierta la aplicacion por 10 minutos sin interactuar con la misma.

### Resultado Esperado: 
La aplicacion redirige a la pantalla principal (Inicio) porque la sesion se cerró por inactividad
### Resultado Actual: 
No se cierra la sesión por inactividad nunca.
### Trazabilidad - Historia de Usuario:
-  #22 
- [#TC007 - Inicio de sesion](https://docs.google.com/spreadsheets/d/1oLs9nl9yfKZ5oEMqW4MweW50L_LxiZblQr5aiT6zoC8/edit?usp=sharing)

**Comment by MonicaAntich** [comment]
Se realiza el cierre de sesion por inactividad
https://youtu.be/HIPpK-g44rI
